# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-03 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=15)),
                ('ask', models.TextField()),
                ('number', models.CharField(max_length=30)),
            ],
        ),
    ]
