# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-05 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200903_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
    ]
